# Generated by Django 4.2.7 on 2025-01-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_property_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_img',
            field=models.ImageField(upload_to='property_img/'),
        ),
    ]
