# Generated by Django 4.2.7 on 2025-02-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_property_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
