# Generated by Django 5.1.6 on 2025-02-20 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_location_bookreq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favourite', models.BooleanField(default=False)),
                ('favowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favowner', to=settings.AUTH_USER_MODEL)),
                ('favproperid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favproperid', to='property.property')),
            ],
        ),
    ]
