# Generated by Django 5.1.6 on 2025-02-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='is_favourite',
            field=models.BooleanField(default=True),
        ),
    ]
