# Generated by Django 5.0.2 on 2025-04-01 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_favourites_is_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReqStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('reqanstime', models.DateTimeField(auto_now_add=True)),
                ('bookreqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.bookreq')),
            ],
        ),
    ]
