# Generated by Django 5.2 on 2025-04-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
